### ISSUE TITLE
Switching to 64 bit mode

### ISSUE THREAD

**Issue by souvik1997** [blacksmithgu/AsyncOS#1]
Switching to 64 bit mode is rather painful, since it requires (1) switching to 32 bit mode, with a proper 32 bit IDT/GDT, and (2) once you're in 32 bit mode, you need to set up a 64 bit IDT/GDT to switch to long mode.

One way to directly use long mode is to use UEFI, but that has its own set of issues (namely hardware compatibility and silly things like using Microsoft's calling convention). If we decide to use UEFI this may be a good resource: https://github.com/thepowersgang/rust_os

Of course, none of this is helpful for SMP since we have to do the 16 bit -> 32 bit -> 64 bit incantations anyway for CPUs other than CPU 0 anyway. :smile:

Edit: I read the part about switching to long mode on Philip Oppermann's blog, and he seems to skip the 32 bit GDT/IDT part. This would work if we don't plan on supporting SMP.

**Comment by blacksmithgu** [comment]
Yeah, it looks like the OS on the blog is single-core only (at least at the moment) as it doesn't ever bother setting up the GDT or IDT.

I'll take a look at UEFI, but compatibility with it is indeed something _ugly_. Our other option is to simply ask Multiboot to put us in 16-bit mode and then bootstrap ourselves up to 64-bits via assembly before finally switching to rust.

**Comment by blacksmithgu** [comment]
Also, I've invited you to Gitter, which will probably make these kinds of discussions easier.

**Comment by blacksmithgu** [comment]
As of commit 4812069a34ed1764b0ae5cf7b0dffe59c0426aa4, the kernel switches to 64-bit using a built in 32-bit bootstrap section which is loaded into the very bottom of physical memory (eg, at 0x7C00).
